<?php
/**
 * Created by PhpStorm.
 * User: admin
 * Date: 2018/8/22
 * Time: 10:03
 */

namespace app\api\controller\v1;
use app\api\service\Auth;
use app\api\controller\BaseController;
use app\lib\Aes;
use app\api\model\User;
use app\lib\exception\ParameterException;

/**
 * 该类用于作为区分调用的接口是否需要登录验证
 * Class AuthBase
 * @package app\api\controller\v1
 */
class AuthBase extends BaseController
{
    /**
     * 登录用户的基本信息
     * @var array
     */
    public $user = [];

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $isLogin = $this->isLogin();
        if(!$isLogin){
            throw new ParameterException([
                'msg'=>'您还没有登录，请先登录',
                'code'=>'401'
                ]
            );
        }
    }

    /**
     * 判断用户是否登录并且将用户信息赋予user成员变量
     * @return bool
     */
    public function isLogin(){
        $encryptToken = Auth::$header['access_user_token'];
        if(empty($encryptToken)){
            return false;
        }

        $obj = new Aes();
        $accessUserToken = $obj->decrypt($encryptToken);

        if(empty($accessUserToken)|| !preg_match('/||/',$accessUserToken)){
            return false;
        }

        list($token,$id) = explode('||',$accessUserToken);
        $user = User::get(['token'=>$token]);

        if(!$user || $user->status != 1){
            return false;
        }

        //判断时间是否过期
        if(time()>$user->time_out){
            return false;
        }

        $this->user = $user;
        return true;
    }
}